### ISSUE TITLE
生成html时报错

### ISSUE THREAD

**Issue by xubai2001** [Meekdai/Gmeek#194]
### 报错信息：
```
{'bug': '#d73a4a', 'documentation': '#0075ca', 'duplicate': '#cfd3d7', 'enhancement': '#a2eeef', 'help wanted': '#008672', 'invalid': '#e4e669', 'question': '#d876e3', 'test': '#c2e0c6', '仓输入法': '#0e8a16'}
GitHub Pages URL:  https://xubai-owo.github.io/
blogBase is exists and issue_number!=0, runOne
====== start create static html ======
Traceback (most recent call last):
  File "Gmeek.py", line 473, in <module>
    blog.runOne(options.issue_number)
  File "Gmeek.py", line 426, in runOne
    self.createPostHtml(self.blogBase[listJsonName]["P"+number_str])
KeyError: None
Error: Process completed with exit code 1.
```

**Comment by hst1189** [comment]
@xubai2001 
没加标签
![image](https://github.com/user-attachments/assets/8b78b502-70cd-480a-bcb7-e8939823a93b)

**Comment by xubai2001** [comment]
感谢！是我疏忽了

**Comment by hst1189** [comment]
我刚用的时候，也经常漏   

可以向 @Meekdai 提议     
label没指定的话， 能否生成一个默认的，例如 label=`未指定` ，  可以避免 老是报 Gmeek.py错误

**Comment by Meekdai** [comment]
@hst1189 你知道为什么必须要添加至少一个label吗？如果不添加，别人在你仓库提交一个issue也会被抓取生成为文章。
