### ISSUE TITLE
can't generate post recently

### ISSUE THREAD

**Issue by suredream** [Meekdai/Gmeek#21]
Used to work very well. However, github action fails as the following error message, any idea?

```
Run cp -r ./* /opt/Gmeek/
{'bug': '#d73a4a', 'duplicate': '#cfd3d7', 'enhancement': '#a2eeef', 'fiction': '#e4e669', 'good first issue': '#7057ff', 'post': '#0075ca', 'question': '#d876e3', 'read': '#008672', 'wontfix': '#ffffff'}
blogBase is exists and issue_number!=0, runOne
====== start create static html ======
Traceback (most recent call last):
  File "Gmeek.py", line 3[20](https://github.com/suredream/suredream.github.io/actions/runs/7243109274/job/19729455536#step:8:21), in <module>
    blog.runOne(options.issue_number)
  File "Gmeek.py", line 293, in runOne
    listJsonName=self.addOnePostJson(issue)
  File "Gmeek.py", line [25](https://github.com/suredream/suredream.github.io/actions/runs/7243109274/job/19729455536#step:8:26)1, in addOnePostJson
    self.blogBase[listJsonName][postNum]["style"]=self.blogBase["style"]
KeyError: 'style'
Error: Process completed with exit code 1.
```

**Comment by Meekdai** [comment]
Sorry, some code has been fixed in previous updates. You can fix this error by following the method below.
```Actions->build Gmeek->Run workflow->Run workflow```
For detailed information, please refer to https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html

**Comment by ShixiangWang** [comment]
我也是这个问题，按照这个操作也没有解决呢

https://github.com/OncoHarmony-Network/OncoHarmony-Network.github.io/actions/runs/7297773557/job/19887814611#step:9:26

**Comment by Meekdai** [comment]
> 我也是这个问题，按照这个操作也没有解决呢
> 
> https://github.com/OncoHarmony-Network/OncoHarmony-Network.github.io/actions/runs/7297773557/job/19887814611#step:9:26

你没有按这个操作执行啊，手动全局生成一次就行了。`Run workflow` 要点到那个绿色的按钮才行。

**Comment by ShixiangWang** [comment]
> > 我也是这个问题，按照这个操作也没有解决呢
> > https://github.com/OncoHarmony-Network/OncoHarmony-Network.github.io/actions/runs/7297773557/job/19887814611#step:9:26
> 
> 你没有按这个操作执行啊，手动全局生成一次就行了。`Run workflow` 要点到那个绿色的按钮才行。

感谢回复和提醒，的确如此，我之前每次在 failed 的里面 re-run 的。

**Comment by ShixiangWang** [comment]
好奇问一下，这两种区别是什么？我之前以为等同的。。。

**Comment by Meekdai** [comment]
> 好奇问一下，这两种区别是什么？我之前以为等同的。。。

只有用`Run workflow`这个按钮执行的是全局重新生成，其他的都只是单篇文章生成，如果是`config.json`文件修改，必须要全局再生成一次才行。`re-run`这种都还是生成单篇文章的操作，所以在workflow里显示的标题就是issue的标题，而全局则显示的是`build Gmeek`。

**Comment by ShixiangWang** [comment]
理解了，谢谢解惑💗
