### ISSUE TITLE
Error happen when generate new html stage

### ISSUE THREAD

**Issue by thisjok** [Meekdai/Gmeek#26]
自动部署时，在"Generate new html"阶段出错，错误如下：
`Run cp -r ./* /opt/Gmeek/
{'Blog test': '#ED336B', 'bug': '#d73a4a', 'documentation': '#0075ca', 'duplicate': '#cfd3d7', 'enhancement': '#a2eeef', 'good first issue': '#7057ff', 'help wanted': '#008672', 'invalid': '#e4e669', 'question': '#d876e3', 'Team work': '#08EE35', 'wontfix': '#ffffff'}
Traceback (most recent call last):
  File "Gmeek.py", line 320, in <module>
    blog.runOne(options.issue_number)
  File "Gmeek.py", line 293, in runOne
    listJsonName=self.addOnePostJson(issue)
  File "Gmeek.py", line 251, in addOnePostJson
    self.blogBase[listJsonName][postNum]["style"]=self.blogBase["style"]
KeyError: 'style'
blogBase is exists and issue_number!=0, runOne
====== start create static html ======
Error: Process completed with exit code 1.`

**Comment by Meekdai** [comment]
@thisjok 
出现这种问题一般通过手动全局生成一次都可以解决，具体可见 https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html
另外我看到你现在已经自动部署成功了，是哪里的问题导致的？可以分享一下，给之后遇到这个问题的伙伴一个参考，谢谢。
